### VARIABLES

@devtoken = {{$dotenv DEV_TOKEN}}

@devUserId = {{$dotenv DEV_USER_ID}}

@adminToken = {{$dotenv ADMIN_TOKEN}}

### GET /

GET http://localhost:3000/

### POST /register (register a new user)

POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "name": "New User",
    "email": "testmail2@gmail.com",
    "username": "newuser2",
    "password": "newpassword"
}

### POST /login (login a user)

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "testmail2@gmail.com",
    "password": "newpassword"
}

### POST /login (login with username)

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword"
}

### DELETE /delete (delete a user) (protected)
@deletionId = cma5ltyit00005bzq1qqzpx16
DELETE http://localhost:3000/auth/delete/{{deletionId}}
Content-Type: application/json
Authorization: {{adminToken}}

