### VARIABLES

@devToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtYTNwODRlaTAwMDB0c3MwYnZ2anRtYmgiLCJpYXQiOjE3NDYxMDQ4NDQsImV4cCI6MTc0NjE5MTI0NH0.FdmQgtHcFw_IBQirXbFC38dCvtsQsPLoJQl1uMwvrO4

@devUserId = cma3p84ei0000tss0bvvjtmbh

### GET /

GET http://localhost:3000/

### POST /register (register a new user)

POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "name": "New User",
    "email": "testmail@gmail.com",
    "username": "newuser",
    "password": "newpassword"
}

### POST /login (login a user)

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "testmail@gmail.com",
    "password": "newpassword"
}

### POST /login (login with username)

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword"
}

### GET /semesters (get all semesters) (protected)

GET http://localhost:3000/semesters 
Content-Type: application/json
Authorization: {{devToken}}

{
    "userId": "{{devUserId}}"
}

### GET /semesters (get a year by semester string) (protected)

GET http://localhost:3000/semesters/semester
Content-Type: application/json
Authorization: {{devToken}}

{
    "userId": "{{devUserId}}",
    "semester": "24"
}

### POST /semesters (create a new semester) (protected)

POST http://localhost:3000/semesters 
Content-Type: application/json
Authorization: {{devToken}}

{
    "semester": "2026/27",
    "userId": "{{devUserId}}"
}